@humidify.Api_HostAddress = http://localhost:5091

POST {{humidify.Api_HostAddress}}/api/sensor/reading
Content-Type: application/json


GET {{humidify.Api_HostAddress}}/api/sensor/latest
Accept: application/json